name: tests
on: [ push ]

jobs:
  provide_changed_packages:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    # see https://stackoverflow.com/a/62953566/1348344
    runs-on: ubuntu-18.04

    steps:
      - name: Set Environment
        run: |
          #echo "BUILD_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "BUILD_TAG=v3.3.1" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      # load current composer.lock
      - id: currentLock
        name: Gather latest package information
        run: |
          OUT=$(jq --slurp '[.[].packages[] | select(.name | contains("ezsystems") or contains("ibexa")) | [.name, .version] | { name: (.[0]), version: .[1] }]' composer.lock)
          echo "::set-output name=lock::$( echo "$OUT" | sed ':a;N;$!ba;s/\n/%0A/g' )"

      - name: Get previous release tag based on type
        id: prevrelease
        uses: ibexa/version-logic-action@master
        with:
          currentTag: ${{ env.BUILD_TAG }}

      # checkout previous tag
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.prevrelease.outputs.previousTag }}

      # load previous composer.lock
      - id: previousLock
        name: Gather previous package information
        run: |
          OUT=$(jq --slurp '[.[].packages[] | select(.name | contains("ezsystems") or contains("ibexa")) | [.name, .version] | { name: (.[0]), version: .[1] }]' composer.lock)
          echo "::set-output name=lock::$( echo "$OUT" | sed ':a;N;$!ba;s/\n/%0A/g' )"

      # do some magic comparing those outputs
      - id: output_data
        name: Do comparison and output JSON with changes
        run: |
          FILE1=$(mktemp)
          FILE2=$(mktemp)
          cat > $FILE1 <<'EOF'
          ${{ steps.previousLock.outputs.lock }}
          EOF
          cat > $FILE2 <<'EOF'
          ${{ steps.currentLock.outputs.lock }}
          EOF
          OUT=$(jq -s 'flatten | group_by(.name)' $FILE1 $FILE2 | jq -s '[ .[][] | {name: (.[0].name), versions: [ .[0].version, .[1].version ] | unique} | select(.versions | length > 1) ]')
          echo "::set-output name=matrix::$( echo "$OUT" | sed ':a;N;$!ba;s/\n/%0A/g' )"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  get_package_changelogs:
    needs: provide_changed_packages

    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_changed_packages.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - run: |
          echo ${{ matrix.package }}

      - # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@1.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'symplify'
          split-repository-name: '${{ matrix.package }}'
          user-name: "kaizen-ci"
          user-email: "info@kaizen-ci.org"
          branch: "main"